services:
  mysql:
    image: mysql:8.0
    container_name: assment7_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: assment7_mysql
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3306:3306"
    volumes:
      - blog_mysql_data:/var/lib/mysql

volumes:
  blog_mysql_data:
